---
version: 2
jobs:
  test:
    docker:
      - image: aegypius/repoman
        entrypoint: [/bin/sh]
    working_directory: /overlay
    environment:
      FEATURES: -ipc-sandbox -network-sandbox -pid-sandbox
    steps:
      - checkout
      - run: repoman -dx full


workflows:
  version: 2
  commit:
    jobs:
      - test
