---
name: New ebuild
on: [push]
#on:
#  schedule:
#    - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create a new ebuild
        run: |
          set -x
          if ./is_latest.sh; then
            exit 0
          fi
          echo "::set-env name=latest_verion::$(./is_latest.sh || exit 0)"
          ./update_ebuilds.sh
          docker pull aegypius/repoman
          docker run --rm -it -v $(pwd):/overlay aegypius/repoman manifest
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "net-im/zoom-${latest_version}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ebuild-${{ env.latest_version }}
      - name: Initialize Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ebuild-${{ env.latest_version }}
          destination_branch: master
          pr_title: ebuild for net-im/zoom-${{ env.latest_version }}
          pr_body: >
            Hello!

            There is a new version of Zoom available for download. Please
            review this ebuild so that it can be published to the overlay.
