---
name: Test
on: [push, pull_request]

jobs:
  repoman:
    runs-on: ubuntu-latest
    container:
      image: aegypius/repoman
      env:
        FEATURES: -ipc-sandbox -network-sandbox -pid-sandbox
    steps:
      - uses: actions/checkout@master
      - name: repoman full check
        run: repoman -dx full
